[package]
name = "shared"
version = "0.1.0"
authors = ["Quigles1337"]
edition = "2021"

[dependencies]
cosmwasm-schema = "1.5.0"
cosmwasm-std = "1.5.0"
schemars = "0.8.16"
serde = { version = "1.0.195", default-features = false, features = ["derive"] }
